apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
  selector:
    app: server